package AdderApp;

/**
* AdderApp/AdderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adder.idl
* Thursday, 8 May, 2025 12:30:11 AM IST
*/

public final class AdderHolder implements org.omg.CORBA.portable.Streamable
{
  public AdderApp.Adder value = null;

  public AdderHolder ()
  {
  }

  public AdderHolder (AdderApp.Adder initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdderApp.AdderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdderApp.AdderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdderApp.AdderHelper.type ();
  }

}
