package AdderApp;


/**
* AdderApp/Adder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adder.idl
* Thursday, 8 May, 2025 12:30:11 AM IST
*/

public interface Adder extends AdderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Adder
