package AdderApp;


/**
* AdderApp/AdderHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adder.idl
* Thursday, 8 May, 2025 12:30:11 AM IST
*/

abstract public class AdderHelper
{
  private static String  _id = "IDL:AdderApp/Adder:1.0";

  public static void insert (org.omg.CORBA.Any a, AdderApp.Adder that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AdderApp.Adder extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AdderApp.AdderHelper.id (), "Adder");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AdderApp.Adder read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AdderStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AdderApp.Adder value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AdderApp.Adder narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AdderApp.Adder)
      return (AdderApp.Adder)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AdderApp._AdderStub stub = new AdderApp._AdderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AdderApp.Adder unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AdderApp.Adder)
      return (AdderApp.Adder)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AdderApp._AdderStub stub = new AdderApp._AdderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
